services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "uv", "run", "gunicorn", "app.main:create_app()", "-b", "0.0.0.0:8080", "-k", "uvicorn_worker.UvicornWorker", "-w", "${WORKERS_QUANTITY}" ]
    ports:
      - 8080:8000
    volumes:
      - migrations-data:/app/migrations/versions
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:17-bookworm
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-U", "${DB_USER}", "-d", "${DB_NAME}" ]
      interval: 5s
      timeout: 3s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:8-bookworm
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  migrations-data: {}
  postgres-data: {}
  redis-data: {}
  pgadmin-data: {}
